apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  volumes:
  - name: test-volume
    emptyDir: {}
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: alpine
    command:
    - /bin/sh
    args: ["-c","while true; do date >> /var/simple/file.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /var/simple
      name: test-volume 
  restartPolicy: Always
