apiVersion: v1
kind: Service
metadata:
  name: clusterip-nginx
spec:
  # modify replicas according to your cas
  selector:
    app: nginx    
  type: ClusterIP
  ports:
   - port: 80
     protocol: TCP         
     targetPort: 80
     

  
