apiVersion: v1
kind: Service
metadata:
  name: loadbal-ngnix
spec:
  # modify replicas according to your cas
  selector:
    app: nginx    
  type: LoadBalancer
  ports:
   - port: 80
     protocol: TCP         
     targetPort: 80
     

  
