apiVersion: v1
kind: Service
metadata:
  name: nodeport-nginx
spec:
  # modify replicas according to your cas
  selector:
    app: nginx    
  type: NodePort
  ports:
   - port: 80
     protocol: TCP         
     targetPort: 80
     nodePort: 31575

  
